name: NHS Prescribing ETL Data Pipeline

on:
  push:
    branches:
      - main

jobs:
  run-tests:
    name: run-tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Set Up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12' 
        
      - name: Print Hello
        run: echo "GitHub Actions set up successfully!"

